### ISSUE TITLE
Garage ignores pre-created log directory structure + Integration with Hydra

### ISSUE THREAD

**Issue by amolchanov86** [rlworkgroup/garage#1219]
It seems that the garage creates another dictionary (with postfix _1) if the pre-created directory structure exists. 
I boiled it down to the flag `exist_ok=True` in os.makedir in the ExperimentTemplate.
For example, the Hydra framework creates the folder structure on its own and places all configs inside (and other nice things), but when the garage is invoked it simply cleans up everything.

Garage version: **v2020.02.0rc2**

Here is the example to recreate:
```
#!/usr/bin/env python
import sys, os
import hydra
from omegaconf import DictConfig
from omegaconf import OmegaConf

## GARAGE
from garage import wrap_experiment

@hydra.main(config_path="config/default.yaml", strict=True)
def experiment(cfg : DictConfig) -> None:
    print(cfg.pretty())

    ## Saving command line executing the script
    # or doing whatever you are interested to do ahead
    cmd = " ".join(sys.argv)
    with open(os.path.join(os.getcwd(), "cmd.sh"), "w") as cmdfile:
        cmdfile.write("#!/usr/bin/bash\n")
        cmdfile.write(cmd)

    ## Converting DictConfig to normal dict
    cfg = OmegaConf.to_container(cfg)

    ## Actual experiment
    @wrap_experiment(log_dir=os.getcwd(), snapshot_mode="all", snapshot_gap=None)
    def run_task(ctxt, cfg):
        print("Running my alg ...")
        pass

    run_task(cfg=cfg)


if __name__ == "__main__":
    experiment()
```
The file assumes that you have created config/default.yaml file where the script is located
Simplest example of the default.yaml

```
seed: 1
env:
  class: MyEnv
hydra:
  run:
    dir: ./_results_temp/${env.class}/${now:%Y-%m-%d}/${hydra.job.override_dirname}__${now:%H-%M-%S}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: '__'
        exclude_keys: []
```

Installing hydra: 
```
pip install hydra-core --upgrade
```

Website: https://hydra.cc/docs/intro

The solution should be to just introduce the option `keep_existing_folders=True` in the ExperimentTemplate and the experiment wrapper and propagate it to `exist_ok`.
